### ISSUE TITLE
tab_completeness error m_str_extents_

### ISSUE THREAD

**Issue by ben-wetherill** [massbays-tech/MassWateR#11]
After loading the resdat and dqocomdat files from the example files, I get the following error for type summary:

`> tab_completeness(resdat,dqocomdat,type="summary")`
Error in m_str_extents_(x, fontname, fontsize, bold, italic, fontfile) : 
  function 'Rcpp_precious_remove' not provided by package 'Rcpp'

Also, if I run without type, R freezes
`> tab_completeness(resdat,dqocomdat)`

**Comment by fawda123** [comment]
@ben-wetherill unfortunately I cannot reproduce the error on my end and it is not being triggered in any of the package checks.  

It might be related to this issue? https://support.rstudio.com/hc/en-us/articles/4415936301335-Resolving-Rcpp-precious-remove-error Try reinstalling the Rcpp package and running `tab_completeness()` again.

**Comment by ben-wetherill** [comment]
I reinstalled the Rcpp package and restarted R, and that resolved the issue.

**Comment by fawda123** [comment]
@ben-wetherill ok, that's unfortunate it's a dependency issue since users may run into the same problem.  Most of those problems should be taken care of by installing the package from R-universe (https://massbays-tech.r-universe.dev/ui#package:MassWateR) as noted in the package website on GitHub.  The R-universe service is great because it creates a binary/compiled version of the package that handles the dependencies much better than installing from source via GitHub (e.g., `remotes::install_github('massbays-tech/MassWateR')`).
