### ISSUE TITLE
How to load my own results file

### ISSUE THREAD

**Issue by ben-wetherill** [massbays-tech/MassWateR#13]
How would I load my own results file?  I tried replacing the respth argument with a local path, but it doesn't seem to work.

```
respth <- "D:/Documents/ExampleResults_final_4-28-22.xls"
resdat <- read_results(respth)
Error: `path` does not exist: ‘D:/Documents/ExampleResults_final_4-28-22.xls’
```

**Comment by fawda123** [comment]
@ben-wetherill, that should work... is the path right?  What happens when you run this? 
```r
file.exists(""D:/Documents/ExampleResults_final_4-28-22.xls")
```

**Comment by ben-wetherill** [comment]
You're right.  The path was wrong.  I had the wrong suffix .xls instead of .xlsx.
read_results() worked with my file, but it still wanted the column heading of Results Depth Category.  This needs to be changed to Activity Relative Depth Name.

**Comment by fawda123** [comment]
@ben-wetherill good, glad that was sorted.  Do you mean the column G header name should be "Activity Relative Depth Name" instead of "Relative Depth Category"? If so, I can change the system file and the check in `check_results()`.
![image](https://user-images.githubusercontent.com/3086881/167620786-07c28093-d012-41dd-98c6-db59f66b66bd.png)

**Comment by ben-wetherill** [comment]
Yes.  That's correct.
