### ISSUE TITLE
Create function to compile qc outputs in a report with user inputs

### ISSUE THREAD

**Issue by fawda123** [massbays-tech/MassWateR#20]
Need to call rmarkdown render to word file with parameters for results and dqo files, additional arguments based on user preferences, e.g., warnings, font sizes, etc.  The rmarkdown templates lives in inst/rmd.

**Comment by ben-wetherill** [comment]
I tested this qcMWRreview() function.  This is pretty fancy!

I received a warning message "package 'flextable' was built under R version 4.0.5 ".

Here are some other things I noticed:

1. In the first page, frequency, completeness, MDL, and UQL, a decimal (.0) was added for all values that were provided with no decimal (such as 2 or 10).  It would be preferable to not display this decimal.
2. In the first page, MDL values below 0.1 show as 0.0.  Should show as 0.01, etc.
3. For the Prepared by, QAPP Version, and Notes sections, is it possible to make these act like a table cell instead of just underscored spaces?  If it was a table, then when the user typed in text the spaces wouldn't move and extend the field.
4. You can start a new page for QC Frequencies, QC Accuracy Summary, Data Completeness, and QC Raw Data.  Currently QC Frequencies is not doing this.
5. Can you add an option to turn off the QC Raw Data section?  That can become very long, so people might not always want to include it?
6. I think the default should be warn=TRUE and I think the warnings should display in the R console, not in the document.  But it would not be ideal to have the same warnings repeat for each section.  Is it possible to consolidate the warnings?

**Comment by ben-wetherill** [comment]
Should we give the user the ability to define the name of the output file?

**Comment by fawda123** [comment]
@ben-wetherill the remaining issues for the review report should all be addressed now, including the option to change the file name.  Please have a look when able and close the issue if everything looks good.

**Comment by ben-wetherill** [comment]
All of the previous issues have been resolved.

A couple new formatting requests:
Actually, I'm a confused, because the first time I ran the report, I had the following issues.  But the second and third times I ran it, these issues didn't appear.  Everything was fine, except #5.  **So, only #5 needs to be adjusted.**

1. Can the table rows be made narrower?  It looks like all of the text is set up with 5pt spacing before and after each paragraph, which makes the tables quite long.  I think it should be reduced to 0pt spacing before and after.  And, actually, row height might be a good parameter to allow the user to define in the function.  If so, a minimum row height of 0.2" would be a good default. 
2. In QC frequencies, it would be good to make the Parameter column width 1.15" so that Sp Conductance doesn't wrap.  That is the longest common parameter.  Also, same in the QC frequencies percent table.
3. In QC frequencies, you can put a space in the header "Number of Dups/Blanks/ Spikes" before Spikes so that the column doesn't have to be so wide.
4. In QC accuracy percent table, make the Parameter column width 1.15".
5. In Data Completeness table, make the Parameter column width 1.15".  Also, add a space in the "Hit/ Miss" header so that the column doesn't need to be so wide.
6. In the QC Raw Data table, make the Parameter column width 1.15".

**Comment by fawda123** [comment]
@ben-wetherill thanks, I also noticed that issue with the formatting on first render. I don't know why it only happens then, but it's fixed now. I also made the modifications to the completeness table.

**Comment by ben-wetherill** [comment]
Everything looks good.
