### ISSUE TITLE
Create outliers function

### ISSUE THREAD

**Issue by fawda123** [massbays-tech/MassWateR#22]
* User specifies plot grouping (by Month, or by Site).
* User can specify one parameter, or default is to produce one graph for each parameter that is listed in the DQO Frequency/Completeness file.
* Return a boxplot in the following format, showing all months with data or all sites with data.
* In month plot, provide site labels for outliers.  In site plot, provide date labels for outliers.
* Also, return a text list of all outliers with parameter, date, site, and value (in console or file).
* Define outliers per standard ggplot definition.
* Add thresholds option T/F

Other considerations: 

* Filter by date range
* Saving output option

**Comment by ben-wetherill** [comment]
This is looking great.

Here are some feedback...

1. In the vignette, this probably shouldn't be called "analysis functions".  I think it should be separate from the analysis functions.  I would call it "reasonability checks".
2. The outlier labels can be a smaller font.
3. The log scale outliers seem to be working strangely.  For E.coli, there is a point in June that shows a red dot at 10 but doesn't have a label and doesn't show on the outlier table.  This should have a label.  Also, there are a number of points within the whisker in July and August that show no dots but do show labels.  These probably shouldn't be labeled.
4. Are the BDL values being included?  They should be included at MDL.

**Comment by ben-wetherill** [comment]
Function review feedback:

1. I guess the jitter functionality doesn't work for outliers.  anlzMWRoutlier(resdat,param="E.coli", acc=dqoaccdat, type="jitterbox", group="month").  Not critical, but if fixable it would be nice.
2. The group parameter should be required, because that changes the list of outliers, and if you run the function for outliers=TRUE, then you don't necessarily know what the grouping is.  There is a similar issue for yscl, but I don't think that should be required, because I think the auto setting is logical enough for people to assume.

All the other issues mentioned above look good now.

**Comment by fawda123** [comment]
Should all be addressed now - outliers are jittered for the appropriate `type` argument and the `group` argument is required.

**Comment by ben-wetherill** [comment]
Wow!  Everything looks great!

**Comment by fawda123** [comment]
@ben-wetherill I've finished a working version of the plot export function for outliers - check it out here and let me know what you think! https://massbays-tech.github.io/MassWateR/articles/outlierchecks.html#save-all-outlier-results

**Comment by ben-wetherill** [comment]
This is great!  It works perfectly.

Can you add a line-space between graphs?

**Comment by fawda123** [comment]
@ben-wetherill line is added for Word output.

**Comment by ben-wetherill** [comment]
Looks great!
