### ISSUE TITLE
Create time series trend function

### ISSUE THREAD

**Issue by fawda123** [massbays-tech/MassWateR#24]
Can be similar to seasonal function in plot format, but trend is continuous. Need to include:

* Most options from seasonal function
* Date filter option
* Site filter option
* Parameter required
* Result Attribute option
* Replace BDL, AQL with appropriate values
* Add threhsold lines, specify marine or fresh
* Group by site or result attributes
* Options by group for all sites, averages all sites with grouping by week or month (plus CI)

**Comment by fawda123** [comment]
Need to figure out if sites are colored or not if `group = "site"`, if so, how are the color aesthetics handled for the threshold lines? Do we not use a color aesthetic for thresholds and just add a text label?

**Comment by ben-wetherill** [comment]
I'm getting an error

`> anlzMWRdate(resdat, param="TP", acc=dqoaccdat, thresh="fresh",
+             sit = sitedat, group="site")
Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  : 
  Viewport has zero dimension(s)`

**Comment by ben-wetherill** [comment]
I figured out that I can resolve the error above by turning off repel.  So I guess repel needs to be removed from this function.

Other feedback on this function:

1. When grouping by site, the site legend takes up too much space, even when only a few sites are graphed.  There is a large space between the threshold legend and the site legend and then between the site legend and the graph.  Since the site labels are in the graph, it could be possible to just turn off the site legend.  Or, reduce the vertical space between legends.  Or you could put the legend on the right, as in what happens when you add theme_bw().
2. For grouping by location, would it be possible to allow it to run without defining locgroup?  Then by default it would show all the location groups with data.  Not critical, but simpler to run.
3. Could we use another term instead of "location" for group?  It isn't very logical.  Maybe "site_group" or "loc_group".
4. The site labels are cut off on the right hand side of the graph.

**Comment by fawda123** [comment]
I think the error you're getting is described in this issue: https://github.com/slowkow/ggrepel/issues/113 I'm pretty sure it's related to the legend size and it might go away if you increase the plot window in RStudio.  We can remove that option if we think the repel feature is not needed.

The rest of the items should be taken care of.  I did the following:

1. Decreased the vertical spacing on the legend items but also added a `colleg` argument to suppress the site or location group components of the legend, just use `colleg = FALSE`.
1. Specifying `group = "locgroup"` but not any entries to the `locgroup` argument will group sites by all location groups in the site metadata file. Adding values to the `locgroup` argument will still work as before.
1. Changed the character option from "location" to "locgroup"
1. Added an optional `expand` argument if `group = "site"` or `group = "locgroup" that adds a bit more padding on the right, which the user can change as needed, but the default should be fine.

**Comment by ben-wetherill** [comment]
Ok.  Let's set repel to default as FALSE.  Sometimes is might be useful, but we want to avoid criptic errors where possible.

1.  Vertical spacing looks better.  colleg is nice.  Can we set colleg to default as FALSE?  I don't think the legend is that useful if the labels are in the graph.
2.  looks great
3.  looks great
4.  The default is working much better now.  I'm not sure if this expand argument is necessary.  I tried it and I couldn't see any difference.  I doubt the users will remember to use it.

**Comment by fawda123** [comment]
@ben-wetherill should be good now, I set the default values for `colleg` and `repel` to `FALSE`.  

Not sure why you're having issues with the `expand` argument, works fine for me (it requires two values, one for left and right side of the plot):

```
anlzMWRdate(res = resdat, param = 'DO', acc = accdat, sit = sitdat, group = 'locgroup', 
     thresh = 'fresh', locgroup = c('Lower Assabet', 'Upper Assabet'), expand = c(0.05, 0.4)) 
```
![image](https://user-images.githubusercontent.com/3086881/185147902-c1532354-68a4-4254-b262-5528ccba81c1.png)

**Comment by ben-wetherill** [comment]
I got expand to work now.  It only works when repel is FALSE.
Everything looks good now.
