### ISSUE TITLE
Create site analysis function

### ISSUE THREAD

**Issue by fawda123** [massbays-tech/MassWateR#25]
Plotting function for results by site,:

- Most options from seasonal function
- Date filter option
- Site filter option
- Parameter required
- Result Attribute option (grouping option if E. coli or enterococcus)
- Replace BDL, AQL with appropriate values
- Add threhsold lines, specify marine or fresh
- Box plots (w/ jitter option) or barplots (w/ CI if more than one value)

**Comment by ben-wetherill** [comment]
I was not able to get the locgroup to work
`anlzMWRsite(resdat,param="TP",acc=dqoaccdat,sit=sitedat,type="box", thresh="fresh",locgroup = "Upper Assabet")`
`object 'sitdat' not found`

Since you integrated the Dry/Wet analysis into this function, maybe it is not necessary to limit it to just fecal parameters.  It could be used for any parameter and sometimes it might be useful.
For the Dry/Wet analysis, I think it would be best if we could draw some boxes around each group, as in the example in the design document.

**Comment by fawda123** [comment]
Thanks @ben-wetherill, I fixed a bug for the `locgroup` argument.  The rest of your suggestions have also been implemented, i.e., panel boxes for result attribute groupings and making the groupings generic (not just fecal indicators).

**Comment by ben-wetherill** [comment]
Everything is looking good.
Why is the resultatt parameter required.  Couldn't it just automatically group by the available values?

**Comment by fawda123** [comment]
@ben-wetherill, I was just being lazy with the coding.  I updated it to not require the `resultatt` argument.  The facets are grouped by all entries in the `Result Attributes` column if `resultatt` is not included and `byresulttat = TRUE`.

**Comment by ben-wetherill** [comment]
That seems better, but I am getting some errors.

I ran this
`anlzMWRsite(resdat,param="TP",acc=dqoaccdat,sit=sitedat,type="box", thresh="fresh", locgroup = "Sudbury", byresultatt = TRUE)
Error: Location group not found in site metadata file for TP: Sudbury, none available`
The error is really because there are no result attributes defined for TP in Sudbury.  Could you change the error message?

Actually, it might be better if the graphs included values with no result attribute (ie NA values).  That way you wouldn't get an error if none were defined and the user would also be able to see if there were values where they forgot to enter a result attribute.  Also, if for some reason they wanted to have NA values but not show them, they could manually exclude them with the resultatt parameter.

When I run this...
`anlzMWRsite(resdat,param="DO",acc=dqoaccdat,sit=sitedat,type="box", thresh="fresh", byresultatt = TRUE)`
Error in `mutate_cols()`:
! Problem with `mutate()` input `ind`.
x Input `ind` can't be recycled to size 0.
i Input `ind` is `1:n()`.
i Input `ind` must be size 0 or 1, not 2.
Caused by error in `abort_glue()`:
Run `rlang::last_error()` to see where the error occurred.

**Comment by fawda123** [comment]
Thanks for catching that.  I've updated it so that `NA` values will be plotted if there are no entries in the `Result Attribute` column.

**Comment by ben-wetherill** [comment]
Perfect!
