### ISSUE TITLE
qcMWRreview blank pages

### ISSUE THREAD

**Issue by ben-wetherill** [massbays-tech/MassWateR#35]
When I run the qcMWRreview(), I'm now getting blank pages after each section header.  After QC Frequencies, QC Accuracy Summary, and Raw Data.  I first noticed this today after I upgraded to the latest version of R.
`qcMWRreview(resdat,dqoaccdat,dqofrecomdat, "D:/Documents/", output_file = "QCReport", rawdata = FALSE)`

Note that I am also getting the following message after installing our package.  When I upgraded the R version, I removed rtools, which used to be on my computer.  I have not reinstalled it and I didn't notice any issues except the above issue.
`> install.packages('MassWateR')`
`WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:`
`https://cran.rstudio.com/bin/windows/Rtools/`

**Comment by fawda123** [comment]
Hi @ben-wetherill I think fixed the issue with the tables on new pages.  I guess something changed with RMarkdown for the latest version of R.  I had to recreate the Word template, but it should be fixed. 

I also added some text on the website (landing page and "Getting Started") about installing RTools for Windows users.

**Comment by ben-wetherill** [comment]
The blank pages issue is fixed.  Works well now.

I'm not sure about that idea of adding text about installing RTools.  Why do we need RTools at all?  All of the functions seem to work fine for me without RTools.  I only get that message when I run qcMWRreview() but the report seems to generate fine.  I would rather not ask people to load RTools because it is a large load and seems like an unnecessary extra step for users.  Why is it giving that warning?

**Comment by fawda123** [comment]
I think what happened is your library location changed when you upgraded your R version, so the dependencies (sf, dplyr, etc.) for MassWateR are not available in your library path.  The warning is telling you that you need to install RTools to properly install some of the dependencies.  Windows has this weird thing where some packages need to be compiled from the source code for them to install.  I think this only happens if there is a newer version of a dependent package that is not already compiled.  If you don't have RTools it might default to install the older, compiled version of the dependency, which should be fine in most cases.

I see no harm in adding a few sentences on the package web page about RTools.  I don't think we're asking them to install it, but merely providing guidance if they see that message.

**Comment by ben-wetherill** [comment]
I did a little research about this rTools message.  I'm getting the message for any package, not just MassWateR.  According to the web, it seems that the warning now shows up all the time.  But it also is just a warning, so maybe we can tell people they can ignore it.  I found the following two statements in forums:
<This means that if you are going to install packages that need compilation, you also have to install Rtools in your system.>
<Rtools42 is only needed for installation of R packages from source or building R from source.>

Is it safe to say that MassWateR does not require Rtools because it does not need compilation?
The reason I ask is that it is quite a large application.  It takes several minutes to download and several more minutes to install.  I went ahead and installed it, so I don't get the warnings any more, but I want to be able to tell people they only need to install R and RStudio.

**Comment by fawda123** [comment]
@ben-wetherill agreed, it should not be part of the recommended installation process.  Unfortunately, RTools is kind of a beast to install, as you pointed out.  I've worded it in the package website and README as "may be needed", but we can discuss if this is even necessary to include.
