### ISSUE TITLE
Check behavior of QC report generation with gaps in value range

### ISSUE THREAD

**Issue by fawda123** [massbays-tech/MassWateR#57]
The value range column in the DQO accuracy file indicates a range of measurements within which DQOs apply for each parameter.  It was assumed that users would supply value ranges that cover all possible outcomes for a parameter.  This may not be true and the behavior of the QC functions with missing value ranges is unknown.  This needs to be tested.

**Comment by ben-wetherill** [comment]
The behavior of the QC functions is good for tabMWRacc(), but not for tabMWRfre().  If there is a missing value range, then it is best to not report any QC checks for the missing range (as if there were an "na" in the corresponding range).  Then the user will not report better results than reality.  This works correctly for tabMWRacc(), which does not include records in the missing range in **Number of QC Checks** or **Number of Misses**.  It correctly does the same for a missing range or "na".  However, tabMWRfre() misleadingly includes these records in **Number of Dups/Blanks/Spikes**.  It should return the same number as the **Number of QC Checks** in tabMWRacc().

**Comment by ben-wetherill** [comment]
No, the completeness table is unaffected by the DQO objectives.  Qualified records are only defined by the Qualification flag, and in both Completeness and Frequency the Number of Data Records should be the total records regardless of DQO objectives.

**Comment by fawda123** [comment]
Closing this since the warning will be addressed in #58

**Comment by fawda123** [comment]
@ben-wetherill this should be addressed now.  The `tabMWRfre()` function now requires the DQO accuracy file as input and removes any entries in the results file that are outside of the value ranges.  It seems to be working on my end, but you should test it as well.

**Comment by ben-wetherill** [comment]
Getting closer.  The tabMWRfre() **Number of Dups/Blanks/Spikes** is working as I would expect.  **Number of D/B/S** should equal **Number of QC Checks** in tabMWRacc(), and it does.  However, in tabMWRfre() the **Number of Data Records** should not be affected by the DQO Accuracy file.  **Number of Data Records** should be complete regardless of whether a DQO is established.  **Number of Data Records** should match between tabMWRfre() and tabMWRcom().  In the attached files, the number of data records for TP should be 48, but tabMWRfre() shows 39.

[Sample_DQOAccuracy_testing.xlsx](https://github.com/massbays-tech/MassWateR/files/12459771/Sample_DQOAccuracy_testing.xlsx)
[Sample_Results_7-9-23.xlsx](https://github.com/massbays-tech/MassWateR/files/12459772/Sample_Results_7-9-23.xlsx)

**Comment by fawda123** [comment]
@ben-wetherill ok, makes sense. Should be fixed now.

**Comment by ben-wetherill** [comment]
The Number of Data Records looks accurate now, but I have run into some other issues:

1. In the attached files, tabMWRfre() Number of Dups/Blanks/Spikes does not match tabMWRacc() Number of QC Checks for TP Field Duplicates.  tabMWRacc() is correct (should be 4), because it is evaluating the average of the result and reference value (0.04 and 0.02) instead of just the result value.  That's what we agreed a while ago, right?
2. Why is the parameter order different in tabMWRfre() and tabMWRacc()?  It should always be alphabetical, right?  tabMWRfre() doesn't seem to be following that.
3. Field Blanks are not being handled correctly in tabMWRfre().  The attached files should return 0 Dups/Blanks/Spikes or QC Checks for everything.  tabMWRacc() is reporting correctly.  The same issue happens for all of the other QC types if I adjust the DQO Accuracy file accordingly.

[Sample_DQOAccuracy_testing.xlsx](https://github.com/massbays-tech/MassWateR/files/12492298/Sample_DQOAccuracy_testing.xlsx)
[Sample_Results_7-9-23.xlsx](https://github.com/massbays-tech/MassWateR/files/12492300/Sample_Results_7-9-23.xlsx)
[Sample_Sites_5-19-23.xlsx](https://github.com/massbays-tech/MassWateR/files/12492301/Sample_Sites_5-19-23.xlsx)
[Sample_WQXMeta_5-19-23.xlsx](https://github.com/massbays-tech/MassWateR/files/12492302/Sample_WQXMeta_5-19-23.xlsx)
[Sample_DQOFreqComp_5-19-23.xlsx](https://github.com/massbays-tech/MassWateR/files/12492303/Sample_DQOFreqComp_5-19-23.xlsx)

**Comment by fawda123** [comment]
@ben-wetherill, these should be fixed now.  Please verify when able.  

For number 2, this was again caused by an update to dplyr that changed the sorting behavior that handles upper/lower case words differently (presumably to improve performance, https://dplyr.tidyverse.org/news/index.html#breaking-changes-1-1-0).  This should be fixed now.

**Comment by ben-wetherill** [comment]
This looks good now for gaps in the value range.
